/**
 * Per-state campaign metrics — the single source of truth for anything
 * aggregated by geography.
 *
 * National headline figures are sums over this array (reach 20.8M, 5,337
 * agents, 2,455 reports today), so filtering by campaign or state produces
 * correct totals rather than a scaled-down illusion.
 */

export type Zone =
  | "North Central"
  | "North East"
  | "North West"
  | "South East"
  | "South South"
  | "South West";

export const NORTHERN_ZONES: Zone[] = ["North Central", "North East", "North West"];

export interface StateActivity {
  /** Two-letter code — joins to the map geometry in nigeriaGeo.ts. */
  code: string;
  name: string;
  zone: Zone;
  /** Relative field-activity index, 0-100. Drives the choropleth ramp. */
  activity: number;
  /** People reached across all channels. */
  reach: number;
  agents: number;
  /** Net sentiment score, 0-100. */
  sentiment: number;
  reports: number;
  lgas: string[];
}

export const STATE_ACTIVITY: StateActivity[] = [
  {
    code: "LA",
    name: "Lagos",
    zone: "South West",
    activity: 96,
    reach: 1842000,
    agents: 412,
    sentiment: 72,
    reports: 184,
    lgas: ["Ikeja", "Eti-Osa", "Surulere", "Alimosho", "Mushin", "Kosofe", "Ojo", "Ikorodu"],
  },
  {
    code: "FC",
    name: "FCT - Abuja",
    zone: "North Central",
    activity: 88,
    reach: 612000,
    agents: 198,
    sentiment: 65,
    reports: 92,
    lgas: ["AMAC", "Bwari", "Gwagwalada", "Kuje", "Abaji", "Kwali"],
  },
  {
    code: "KN",
    name: "Kano",
    zone: "North West",
    activity: 85,
    reach: 1520000,
    agents: 380,
    sentiment: 58,
    reports: 142,
    lgas: ["Nassarawa", "Fagge", "Dala", "Gwale", "Kumbotso", "Tarauni"],
  },
  {
    code: "KD",
    name: "Kaduna",
    zone: "North West",
    activity: 81,
    reach: 1120000,
    agents: 289,
    sentiment: 54,
    reports: 128,
    lgas: ["Kaduna North", "Kaduna South", "Chikun", "Igabi", "Zaria"],
  },
  {
    code: "RV",
    name: "Rivers",
    zone: "South South",
    activity: 78,
    reach: 980000,
    agents: 245,
    sentiment: 61,
    reports: 110,
    lgas: ["Port Harcourt", "Obio-Akpor", "Eleme", "Okrika", "Ikwerre"],
  },
  {
    code: "OY",
    name: "Oyo",
    zone: "South West",
    activity: 74,
    reach: 890000,
    agents: 220,
    sentiment: 68,
    reports: 96,
    lgas: ["Ibadan North", "Ibadan South-West", "Egbeda", "Akinyele", "Ona-Ara"],
  },
  {
    code: "OG",
    name: "Ogun",
    zone: "South West",
    activity: 72,
    reach: 690000,
    agents: 175,
    sentiment: 69,
    reports: 78,
    lgas: ["Abeokuta South", "Abeokuta North", "Ijebu Ode", "Sagamu", "Ado-Odo/Ota"],
  },
  {
    code: "AN",
    name: "Anambra",
    zone: "South East",
    activity: 71,
    reach: 720000,
    agents: 178,
    sentiment: 70,
    reports: 88,
    lgas: ["Awka South", "Onitsha North", "Onitsha South", "Idemili North", "Nnewi North"],
  },
  {
    code: "DE",
    name: "Delta",
    zone: "South South",
    activity: 70,
    reach: 760000,
    agents: 192,
    sentiment: 63,
    reports: 82,
    lgas: ["Warri South", "Uvwie", "Sapele", "Ughelli North", "Oshimili South"],
  },
  {
    code: "BO",
    name: "Borno",
    zone: "North East",
    activity: 68,
    reach: 410000,
    agents: 110,
    sentiment: 49,
    reports: 71,
    lgas: ["Maiduguri", "Jere", "Konduga", "Mafa", "Bama"],
  },
  {
    code: "ED",
    name: "Edo",
    zone: "South South",
    activity: 66,
    reach: 580000,
    agents: 156,
    sentiment: 66,
    reports: 70,
    lgas: ["Oredo", "Egor", "Ikpoba-Okha", "Ovia North-East", "Esan West"],
  },
  {
    code: "BE",
    name: "Benue",
    zone: "North Central",
    activity: 64,
    reach: 490000,
    agents: 122,
    sentiment: 56,
    reports: 62,
    lgas: ["Makurdi", "Gwer East", "Otukpo", "Gboko", "Vandeikya"],
  },
  {
    code: "AK",
    name: "Akwa Ibom",
    zone: "South South",
    activity: 64,
    reach: 540000,
    agents: 138,
    sentiment: 65,
    reports: 64,
    lgas: ["Uyo", "Ikot Ekpene", "Eket", "Oron", "Abak"],
  },
  {
    code: "KT",
    name: "Katsina",
    zone: "North West",
    activity: 63,
    reach: 590000,
    agents: 142,
    sentiment: 57,
    reports: 64,
    lgas: ["Katsina", "Daura", "Funtua", "Malumfashi", "Mani"],
  },
  {
    code: "EN",
    name: "Enugu",
    zone: "South East",
    activity: 62,
    reach: 540000,
    agents: 140,
    sentiment: 67,
    reports: 64,
    lgas: ["Enugu East", "Enugu North", "Enugu South", "Nsukka", "Udi"],
  },
  {
    code: "ZA",
    name: "Zamfara",
    zone: "North West",
    activity: 62,
    reach: 350000,
    agents: 92,
    sentiment: 48,
    reports: 54,
    lgas: ["Gusau", "Tsafe", "Anka", "Maru", "Shinkafi"],
  },
  {
    code: "IM",
    name: "Imo",
    zone: "South East",
    activity: 62,
    reach: 470000,
    agents: 122,
    sentiment: 69,
    reports: 58,
    lgas: ["Owerri", "Owerri North", "Mbaitoli", "Orlu", "Okigwe"],
  },
  {
    code: "PL",
    name: "Plateau",
    zone: "North Central",
    activity: 60,
    reach: 480000,
    agents: 132,
    sentiment: 55,
    reports: 58,
    lgas: ["Jos North", "Jos South", "Jos East", "Bassa", "Riyom"],
  },
  {
    code: "ON",
    name: "Ondo",
    zone: "South West",
    activity: 60,
    reach: 510000,
    agents: 130,
    sentiment: 65,
    reports: 60,
    lgas: ["Akure South", "Akure North", "Ondo West", "Ikare", "Owo"],
  },
  {
    code: "BA",
    name: "Bauchi",
    zone: "North East",
    activity: 60,
    reach: 510000,
    agents: 128,
    sentiment: 53,
    reports: 58,
    lgas: ["Bauchi", "Azare", "Misau", "Jama'are", "Tafawa Balewa"],
  },
  {
    code: "AB",
    name: "Abia",
    zone: "South East",
    activity: 60,
    reach: 410000,
    agents: 108,
    sentiment: 68,
    reports: 52,
    lgas: ["Umuahia North", "Aba North", "Aba South", "Ohafia", "Isiala Ngwa North"],
  },
  {
    code: "OS",
    name: "Osun",
    zone: "South West",
    activity: 58,
    reach: 470000,
    agents: 124,
    sentiment: 64,
    reports: 56,
    lgas: ["Osogbo", "Ife Central", "Ilesa West", "Ede North", "Iwo"],
  },
  {
    code: "KO",
    name: "Kogi",
    zone: "North Central",
    activity: 58,
    reach: 430000,
    agents: 112,
    sentiment: 57,
    reports: 50,
    lgas: ["Lokoja", "Okene", "Ajaokuta", "Kabba/Bunu", "Idah"],
  },
  {
    code: "SO",
    name: "Sokoto",
    zone: "North West",
    activity: 58,
    reach: 440000,
    agents: 110,
    sentiment: 55,
    reports: 52,
    lgas: ["Sokoto North", "Sokoto South", "Wamakko", "Bodinga", "Tambuwal"],
  },
  {
    code: "CR",
    name: "Cross River",
    zone: "South South",
    activity: 58,
    reach: 410000,
    agents: 110,
    sentiment: 62,
    reports: 50,
    lgas: ["Calabar Municipal", "Calabar South", "Ikom", "Ogoja", "Obudu"],
  },
  {
    code: "NI",
    name: "Niger",
    zone: "North Central",
    activity: 57,
    reach: 470000,
    agents: 118,
    sentiment: 55,
    reports: 52,
    lgas: ["Minna", "Suleja", "Bida", "Kontagora", "Bosso"],
  },
  {
    code: "KW",
    name: "Kwara",
    zone: "North Central",
    activity: 56,
    reach: 410000,
    agents: 108,
    sentiment: 60,
    reports: 48,
    lgas: ["Ilorin West", "Ilorin South", "Ilorin East", "Asa", "Moro"],
  },
  {
    code: "EB",
    name: "Ebonyi",
    zone: "South East",
    activity: 56,
    reach: 320000,
    agents: 88,
    sentiment: 64,
    reports: 42,
    lgas: ["Abakaliki", "Ezza North", "Afikpo North", "Ohaozara", "Ikwo"],
  },
  {
    code: "EK",
    name: "Ekiti",
    zone: "South West",
    activity: 55,
    reach: 320000,
    agents: 92,
    sentiment: 67,
    reports: 42,
    lgas: ["Ado-Ekiti", "Ikere", "Ijero", "Ise/Orun", "Oye"],
  },
  {
    code: "JI",
    name: "Jigawa",
    zone: "North West",
    activity: 55,
    reach: 380000,
    agents: 94,
    sentiment: 56,
    reports: 46,
    lgas: ["Dutse", "Hadejia", "Birnin Kudu", "Kazaure", "Gumel"],
  },
  {
    code: "KB",
    name: "Kebbi",
    zone: "North West",
    activity: 55,
    reach: 320000,
    agents: 84,
    sentiment: 53,
    reports: 42,
    lgas: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  },
  {
    code: "NA",
    name: "Nasarawa",
    zone: "North Central",
    activity: 54,
    reach: 360000,
    agents: 96,
    sentiment: 58,
    reports: 44,
    lgas: ["Lafia", "Karu", "Keffi", "Akwanga", "Nasarawa"],
  },
  {
    code: "BY",
    name: "Bayelsa",
    zone: "South South",
    activity: 54,
    reach: 280000,
    agents: 76,
    sentiment: 60,
    reports: 38,
    lgas: ["Yenagoa", "Brass", "Nembe", "Sagbama", "Ogbia"],
  },
  {
    code: "AD",
    name: "Adamawa",
    zone: "North East",
    activity: 53,
    reach: 320000,
    agents: 88,
    sentiment: 51,
    reports: 44,
    lgas: ["Yola North", "Yola South", "Mubi North", "Numan", "Ganye"],
  },
  {
    code: "GO",
    name: "Gombe",
    zone: "North East",
    activity: 52,
    reach: 290000,
    agents: 80,
    sentiment: 54,
    reports: 40,
    lgas: ["Gombe", "Kaltungo", "Billiri", "Dukku", "Akko"],
  },
  {
    code: "TA",
    name: "Taraba",
    zone: "North East",
    activity: 50,
    reach: 280000,
    agents: 78,
    sentiment: 52,
    reports: 38,
    lgas: ["Jalingo", "Wukari", "Bali", "Gembu", "Takum"],
  },
  {
    code: "YO",
    name: "Yobe",
    zone: "North East",
    activity: 48,
    reach: 260000,
    agents: 70,
    sentiment: 50,
    reports: 36,
    lgas: ["Damaturu", "Potiskum", "Nguru", "Geidam", "Gashua"],
  },
];

/** LGA lookup by state name, derived so it can never drift from the roster. */
export const LGAS_BY_STATE: Record<string, string[]> = Object.fromEntries(
  STATE_ACTIVITY.map((s) => [s.name, s.lgas]),
);
